export let feedbackData = [
  {
    id: 1,
    name: "Ravi",
    city: "Nagpur",
    outlet: "Burger King CP",
    rating: 4,
    message: "Loved the crispy fries and juicy burgers! Ambience was clean and staff was friendly. Perfect for a quick bite.",
    lat: 21.1466,
    lng: 79.0855,
  },
  {
    id: 2,
    name: "Aarti",
    city: "Mumbai",
    outlet: "Haji Ali Juice Center",
    rating: 5,
    message: "Freshest juices I’ve ever had! Must-try the sitaphal and mango flavors. Bit crowded but worth the wait.",
    lat: 19.075983,
    lng: 72.877655,
  },
  {
    id: 3,
    name: "Rohan",
    city: "Delhi",
    outlet: "Karim's Jama Masjid",
    rating: 5,
    message: "Truly authentic Mughlai cuisine! The mutton korma was flavorful and tender. A must-visit for food lovers.",
    lat: 28.650594,
    lng: 77.233239,
  },
  {
    id: 4,
    name: "Neha",
    city: "Pune",
    outlet: "Vaishali Restaurant",
    rating: 4,
    message: "Great for dosas and filter coffee! The place has old-school charm and is always buzzing with students.",
    lat: 18.528984,
    lng: 73.844627,
  },
  {
    id: 5,
    name: "Aman",
    city: "Bangalore",
    outlet: "Toit Brewpub",
    rating: 5,
    message: "Loved the craft beer selection and the live music. Great vibes and perfect for a chill weekend evening.",
    lat: 12.971599,
    lng: 77.594566,
  },
  {
    id: 6,
    name: "Tina",
    city: "Hyderabad",
    outlet: "Paradise Biryani",
    rating: 5,
    message: "If you love biryani, this is heaven! The flavors, quantity and aroma were absolutely mind-blowing.",
    lat: 17.385044,
    lng: 78.486671,
  },
  {
    id: 7,
    name: "Deepak",
    city: "Ahmedabad",
    outlet: "Gordhan Thal",
    rating: 4,
    message: "Traditional Gujarati thali served in royal style. Loved the variety and hospitality. Very filling!",
    lat: 23.022505,
    lng: 72.571365,
  },
  {
    id: 8,
    name: "Kavita",
    city: "Chennai",
    outlet: "Murugan Idli Shop",
    rating: 5,
    message: "Softest idlis I've had with heavenly sambar. Very quick service and authentic flavors from Tamil Nadu.",
    lat: 13.082680,
    lng: 80.270721,
  },
  {
    id: 9,
    name: "Suresh",
    city: "Kolkata",
    outlet: "6 Ballygunge Place",
    rating: 5,
    message: "Exquisite Bengali dishes served with warmth. Loved the fish curry and mishti doi the most!",
    lat: 22.572645,
    lng: 88.363892,
  },
  {
    id: 10,
    name: "Anjali",
    city: "Indore",
    outlet: "Chappan Dukan",
    rating: 4,
    message: "A foodie's paradise with endless snack options. The poha and jalebi combo was just delicious!",
    lat: 22.719568,
    lng: 75.857727,
  },
  {
    id: 11,
    name: "Varun",
    city: "Jaipur",
    outlet: "Laxmi Mishthan Bhandar",
    rating: 5,
    message: "The best place for traditional Rajasthani sweets. Ghewar was mouthwatering and perfectly crisp.",
    lat: 26.912434,
    lng: 75.787270,
  },
  {
    id: 12,
    name: "Sneha",
    city: "Surat",
    outlet: "Gopal Locho Center",
    rating: 4,
    message: "Unique taste of spicy locho and sev. Affordable and very local flavor—must try if in Surat!",
    lat: 21.170240,
    lng: 72.831062,
  },
  {
    id: 13,
    name: "Jatin",
    city: "Bhopal",
    outlet: "Manohar Dairy",
    rating: 4,
    message: "Great spot for chaat and sweets. The rabdi and samosa were especially good and reasonably priced.",
    lat: 23.259933,
    lng: 77.412613,
  },
  {
    id: 14,
    name: "Riya",
    city: "Lucknow",
    outlet: "Tunday Kababi",
    rating: 5,
    message: "Unmatched flavor of kebabs that melt in your mouth. Lucknow's culinary gem, hands down!",
    lat: 26.846695,
    lng: 80.946167,
  },
  {
    id: 15,
    name: "Raj",
    city: "Varanasi",
    outlet: "Kashi Chat Bhandar",
    rating: 4,
    message: "Flavorful chaats and tangy golgappas. Perfect place for a quick snack after a temple visit.",
    lat: 25.317644,
    lng: 82.973915,
  },
  {
    id: 16,
    name: "Meera",
    city: "Chandigarh",
    outlet: "Indian Coffee House",
    rating: 3,
    message: "Simple and nostalgic vibe with decent coffee. Great for long chats and affordable meals.",
    lat: 30.733315,
    lng: 76.779419,
  },
  {
    id: 17,
    name: "Harsh",
    city: "Amritsar",
    outlet: "Kesar Da Dhaba",
    rating: 5,
    message: "Authentic Punjabi food at its best. The dal makhani and lachha paratha were truly divine.",
    lat: 31.634000,
    lng: 74.872261,
  },
  {
    id: 18,
    name: "Pooja",
    city: "Agra",
    outlet: "Pinch of Spice",
    rating: 4,
    message: "Classy interiors and rich, flavorful dishes. Butter chicken was creamy and perfectly spiced.",
    lat: 27.176670,
    lng: 78.008072,
  },
  {
    id: 19,
    name: "Sahil",
    city: "Goa",
    outlet: "Thalassa",
    rating: 5,
    message: "Incredible Greek food with sunset views. A dreamy place for seafood lovers and chill vibes.",
    lat: 15.299326,
    lng: 74.123993,
  },
  {
    id: 20,
    name: "Nidhi",
    city: "Dehradun",
    outlet: "Kalsang Cafe",
    rating: 4,
    message: "Tibetan food with authentic taste. The momos and thukpa were warm and comforting.",
    lat: 30.316495,
    lng: 78.032188,
  },
  {
    id: 21,
    name: "Imran",
    city: "Srinagar",
    outlet: "Ahdoos",
    rating: 5,
    message: "Rich wazwan cuisine that captures Kashmir’s essence. The rogan josh was unforgettable.",
    lat: 34.083656,
    lng: 74.797371,
  },
  {
    id: 22,
    name: "Komal",
    city: "Raipur",
    outlet: "Gullu's Restaurant",
    rating: 4,
    message: "Simple setup but excellent veg thali. Service was fast and food felt like home-cooked.",
    lat: 21.251384,
    lng: 81.629639,
  },
  {
    id: 23,
    name: "Farhan",
    city: "Patna",
    outlet: "Biryani Mahal",
    rating: 4,
    message: "Delicious biryani with a good portion size. Great blend of spices without being overpowering.",
    lat: 25.594095,
    lng: 85.137566,
  },
  {
    id: 24,
    name: "Nisha",
    city: "Udaipur",
    outlet: "Ambrai Restaurant",
    rating: 5,
    message: "Dined by the lake under the stars. A perfect romantic spot with flavorful Indian dishes.",
    lat: 24.585445,
    lng: 73.712479,
  },
  {
    id: 25,
    name: "Aditya",
    city: "Thane",
    outlet: "Mamledar Misal",
    rating: 5,
    message: "The spiciest misal I've had—and I loved it! Super affordable and quick service.",
    lat: 19.218331,
    lng: 72.978088,
  },
  {
    id: 26,
    name: "Rupal",
    city: "Noida",
    outlet: "Barbeque Nation",
    rating: 4,
    message: "Unlimited food with great starters. Loved the pineapple grill and paneer tikka.",
    lat: 28.535517,
    lng: 77.391029,
  },
  {
    id: 27,
    name: "Yash",
    city: "Gwalior",
    outlet: "SS Kachoriwala",
    rating: 4,
    message: "Crispy kachoris with spicy chutney! Quick bite on the go, and always fresh.",
    lat: 26.218287,
    lng: 78.182831,
  },
  {
    id: 28,
    name: "Nikita",
    city: "Jabalpur",
    outlet: "Indian Coffee House",
    rating: 3,
    message: "Old-style place with pocket-friendly menu. Decent coffee and toast sandwiches.",
    lat: 23.181467,
    lng: 79.986408,
  },
  {
    id: 29,
    name: "Akash",
    city: "Ranchi",
    outlet: "Kaveri Restaurant",
    rating: 4,
    message: "Family dining experience with North Indian dishes. Clean and calm environment.",
    lat: 23.344101,
    lng: 85.309563,
  },
  {
    id: 30,
    name: "Divya",
    city: "Kanpur",
    outlet: "Thaggu Ke Laddu",
    rating: 5,
    message: "Famous for a reason! These laddus are sweet, rich, and melt in your mouth. Must visit!",
    lat: 26.449923,
    lng: 80.331871,
  }
];
